# Generated by Django 4.0.6 on 2022-07-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telebot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tele_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=221)),
                ('user_name', models.CharField(max_length=221)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
